[secrets]
secrets_path: /home/pi/printer_data/config/telegram.secrets.conf

[bot]
server: localhost
light_device: chamberlight

[camera]
host: http://localhost:8080/?action=stream
light_control_timeout: 7
fps: 10

[progress_notification]
percent: 10
height: 0
time: 900

[timelapse]
#cleanup: true
#height: 0.2
#time: 60
#target_fps: 15
#min_lapse_duration: 10
#max_lapse_duration: 60
